/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutUploadMovieRouteImport } from './routes/_layout.upload-movie'
import { Route as LayoutSubscribersRouteImport } from './routes/_layout.subscribers'
import { Route as LayoutMoviesRouteImport } from './routes/_layout.movies'
import { Route as LayoutDashboardRouteImport } from './routes/_layout.dashboard'
import { Route as LayoutCategoriesRouteImport } from './routes/_layout.categories'
import { Route as LayoutBroadcastRouteImport } from './routes/_layout.broadcast'
import { Route as LayoutSettingsRouteImport } from './routes/_layout.settings'
import { Route as LayoutUsersRouteImport } from './routes/_layout.users'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutUploadMovieRoute = LayoutUploadMovieRouteImport.update({
  id: '/upload-movie',
  path: '/upload-movie',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSubscribersRoute = LayoutSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMoviesRoute = LayoutMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCategoriesRoute = LayoutCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBroadcastRoute = LayoutBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersRoute = LayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/broadcast': typeof LayoutBroadcastRoute
  '/categories': typeof LayoutCategoriesRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/movies': typeof LayoutMoviesRoute
  '/settings': typeof LayoutSettingsRoute
  '/users': typeof LayoutUsersRoute
  '/subscribers': typeof LayoutSubscribersRoute
  '/upload-movie': typeof LayoutUploadMovieRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/broadcast': typeof LayoutBroadcastRoute
  '/categories': typeof LayoutCategoriesRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/movies': typeof LayoutMoviesRoute
  '/settings': typeof LayoutSettingsRoute
  '/users': typeof LayoutUsersRoute
  '/subscribers': typeof LayoutSubscribersRoute
  '/upload-movie': typeof LayoutUploadMovieRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/broadcast': typeof LayoutBroadcastRoute
  '/_layout/categories': typeof LayoutCategoriesRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/movies': typeof LayoutMoviesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/users': typeof LayoutUsersRoute
  '/_layout/subscribers': typeof LayoutSubscribersRoute
  '/_layout/upload-movie': typeof LayoutUploadMovieRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/broadcast'
    | '/categories'
    | '/dashboard'
    | '/movies'
    | '/settings'
    | '/users'
    | '/subscribers'
    | '/upload-movie'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/broadcast'
    | '/categories'
    | '/dashboard'
    | '/movies'
    | '/settings'
    | '/users'
    | '/subscribers'
    | '/upload-movie'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/_layout/broadcast'
    | '/_layout/categories'
    | '/_layout/dashboard'
    | '/_layout/movies'
    | '/_layout/settings'
    | '/_layout/users'
    | '/_layout/subscribers'
    | '/_layout/upload-movie'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/upload-movie': {
      id: '/_layout/upload-movie'
      path: '/upload-movie'
      fullPath: '/upload-movie'
      preLoaderRoute: typeof LayoutUploadMovieRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/subscribers': {
      id: '/_layout/subscribers'
      path: '/subscribers'
      fullPath: '/subscribers'
      preLoaderRoute: typeof LayoutSubscribersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/movies': {
      id: '/_layout/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof LayoutMoviesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/categories': {
      id: '/_layout/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof LayoutCategoriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/broadcast': {
      id: '/_layout/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof LayoutBroadcastRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users': {
      id: '/_layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutBroadcastRoute: typeof LayoutBroadcastRoute
  LayoutCategoriesRoute: typeof LayoutCategoriesRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutMoviesRoute: typeof LayoutMoviesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutUsersRoute: typeof LayoutUsersRoute
  LayoutSubscribersRoute: typeof LayoutSubscribersRoute
  LayoutUploadMovieRoute: typeof LayoutUploadMovieRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBroadcastRoute: LayoutBroadcastRoute,
  LayoutCategoriesRoute: LayoutCategoriesRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutMoviesRoute: LayoutMoviesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutUsersRoute: LayoutUsersRoute,
  LayoutSubscribersRoute: LayoutSubscribersRoute,
  LayoutUploadMovieRoute: LayoutUploadMovieRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
